### ISSUE TITLE
Setting a property to `0` on an object, throws an error

### ISSUE THREAD

**Issue by joshuef** [node-ffi-napi/weak-napi#13]
Due to the return here: https://github.com/node-ffi-napi/weak-napi/blob/master/lib/weak.js#L104

The setter can mistakenly return `false` if a value of `0` is set on the object in question, which throws an error:

`Uncaught TypeError: 'set' on proxy: trap returned falsish for property '<your property>'`.

**Comment by addaleax** [comment]
Thank you! Do you want to open a PR?

**Comment by joshuef** [comment]
Thanks for the fast response @addaleax !

Just done that right now :D 

https://github.com/node-ffi-napi/weak-napi/pull/14

Let me know if you need any tweaks. Thanks for the rad repo!

**Comment by addaleax** [comment]
Thanks, I’ll close this issue and wait for CI to finish then!

**Comment by joshuef** [comment]
@addaleax I have updated the PR to not add random lines to your codebase :) 🙇
