### ISSUE TITLE
WeakReferences TC39 proposal

### ISSUE THREAD

**Issue by ronag** [node-ffi-napi/weak-napi#18]
I don’t think it would take much to make this library match: https://v8.dev/features/weak-references

**Comment by ronag** [comment]
https://github.com/mhofman/tc39-weakrefs-shim

**Comment by ronag** [comment]
Actually. I think it’s possible to implement the proposal in a more efficient manner.

**Comment by mhofman** [comment]
I'm open to PRs on the shim (I have some updates pending to keep up with spec changes and general improvements).

In node v12 you can actually use native v8 WeakRefs with a flag, but I'd still recommend using my shim to wrap it as their implementation is somewhat broken.

**Comment by ronag** [comment]
@mhofman where does your shim wrap node 12 weakrefs?

**Comment by ronag** [comment]
> I'm open to PRs on the shim (I have some updates pending to keep up with spec changes and general improvements).

I'm mostly unsure about the wrapping. I think this lib with minor modifications could implement it without any wrapping overhead.

**Comment by mhofman** [comment]
There is no WeakFactory in the latest spec version. The global objects are WeakRef and FinalizationGroup.

 `shim()` automatically wraps a global implementation if it finds it broken (unregister not returning Boolean).

My library goes for compliance with the spec. Now that test262 has official tests for WeakRefs (inspired by the tests I wrote for my shim) I'll actually look into running them against my library.
